childwindow-proton: Rebase patches and other things
Frogging-Family/wine-tkg-git pull request #1248
Opened 2024-08-23 14:30 UTC by Artewar67

Should fix this: https://github.com/Frogging-Family/wine-tkg-git/issues/1247

2024-08-23 21:30 UTC, Nanotwerp commented
Tested this PR as a patch and it compiles `Proton-tkg 9.15.r13.gc901884a` successfully!

2024-08-24 01:38 UTC, silverhikari commented
after applying the patch to the latest git, i get "/wine-tkg-git/wine-tkg-patches/misc/childwindow/childwindow-proton: line 103: syntax error: unexpected end of file". i applied the patch by going to the base directory that contains proton-tkg and wine-tkg-kit and running "patch -p1 -i 1248.patch "

2024-08-24 01:40 UTC, Nanotwerp commented
> after applying the patch to the latest git, i get "/wine-tkg-git/wine-tkg-patches/misc/childwindow/childwindow-proton: line 103: syntax error: unexpected end of file". i applied the patch by going to the base directory that contains proton-tkg and wine-tkg-kit and running "patch -p1 -i 1248.patch "

Try `git apply 1248.patch` instead.

2024-08-24 01:44 UTC, silverhikari commented
nope git apply does not change the problem

2024-08-24 01:51 UTC, silverhikari commented
just tried checking out the pull the request and still get the error

2024-08-24 02:02 UTC, Nanotwerp commented
> just tried checking out the pull request and still get the error

I just tried `git apply 1248.patch` on the base folder, and this is the output:

```
1248.patch:151: trailing whitespace.
@@ -1456,10 +1456,23 @@ 
1248.patch:239: trailing whitespace.
@@ -1456,10 +1456,23 @@ 
1248.patch:329: trailing whitespace.
 
1248.patch:334: trailing whitespace.
 
1248.patch:344: trailing whitespace.
 
warning: squelched 102 whitespace errors
warning: 107 lines add whitespace errors.
```

I think you might have copied and pasted the patch instead of using something like `wget https://github.com/Frogging-Family/wine-tkg-git/pull/1248.patch` (or right-clicking and saving the page of the patch) to download it.

2024-08-24 02:08 UTC, silverhikari commented
nope i wget'ed it got the same thing
```1248.patch:151: trailing whitespace.
@@ -1456,10 +1456,23 @@ 
1248.patch:239: trailing whitespace.
@@ -1456,10 +1456,23 @@ 
1248.patch:329: trailing whitespace.
 
1248.patch:334: trailing whitespace.
 
1248.patch:344: trailing whitespace.
 
warning: squelched 102 whitespace errors
warning: 107 lines add whitespace errors.
```

still get the error

2024-08-24 02:10 UTC, Nanotwerp commented
> nope i wget'ed it got the same thing
> 
> ```
> 1248.patch:151: trailing whitespace.
> @@ -1456,10 +1456,23 @@ 
> 1248.patch:239: trailing whitespace.
> @@ -1456,10 +1456,23 @@ 
> 1248.patch:329: trailing whitespace.
>  
> 1248.patch:334: trailing whitespace.
>  
> 1248.patch:344: trailing whitespace.
>  
> warning: squelched 102 whitespace errors
> warning: 107 lines add whitespace errors.
> ```
> 
> still get the error

Those are just trailing whitespace warnings. They're not the error that you got before. You should be able to compile now.

2024-08-24 02:16 UTC, silverhikari commented
this my complete process https://paste.ee/p/YI90G

2024-08-24 02:58 UTC, Nanotwerp requested changes
These two `if` statements should be turned into `elif` statements. Otherwise, [this error](https://github.com/Frogging-Family/wine-tkg-git/pull/1248#issuecomment-2307981305) occurs.

2024-08-24 02:58 UTC, Nanotwerp commented on wine-tkg-git/wine-tkg-patches/misc/childwindow/childwindow-proton
> +	  if git merge-base --is-ancestor c2d46eaa1ef07a2921e5711212e9c5c354f58112 HEAD; then
```suggestion
          elif git merge-base --is-ancestor cb1c03b926ca01619be02f835f382c1dd7d4a478 HEAD; then
```

2024-08-24 02:58 UTC, Nanotwerp commented on wine-tkg-git/wine-tkg-patches/misc/childwindow/childwindow-proton
> +	  if git merge-base --is-ancestor c2d46eaa1ef07a2921e5711212e9c5c354f58112 HEAD; then
```suggestion
          elif git merge-base --is-ancestor cb1c03b926ca01619be02f835f382c1dd7d4a478 HEAD; then
```

2024-08-24 03:03 UTC, Nanotwerp commented
> this is my complete process https://paste.ee/p/YI90G

Oh, I didn't know you were compiling `Wine TKG` instead of `Proton TKG`! I found the cause of the issue. I gave suggestions that fixes it above. Until @Artewar67 implements the changes, you can apply [this patch](https://gist.github.com/Nanotwerp/addb48b35ff91ef70ff0d0fffe0ef91b).

2024-08-24 03:12 UTC, silverhikari commented
yep your fix fixed the issue, thanks!

2024-08-24 10:44 UTC, Tk-Glitch commented
Thanks Artewar67 and Nanotwerp ! :frog: :heart:

2024-08-24 10:44 UTC, merged